services:
    nats:
        image: nats:alpine
        command: ["--jetstream", "--store_dir", "/data", "--http_port", "8222"]
        networks:
            - isolated
        volumes:
            - nats_jetstream:/data
        healthcheck:
            test:
                - CMD-SHELL
                - >
                    wget -qO- --server-response http://localhost:8222/healthz 2>&1 |
                    grep -q 'HTTP/1.1 200 OK'
            interval: 10s
            timeout: 1s
            start_period: 5s

    redis:
        image: redis:8-alpine
        command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]
        volumes:
            - redis_data:/data
        networks:
            - isolated
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 1s
            start_period: 5s

    # The expire service worker is critical for the integrity of the auction service. Other worker
    # servives will depend on this service. This avoids issues such as someone placing a bid after
    # the deadline has passed. Due to this dependency, the worker image is built here once.
    expire-worker:
        build:
            context: .
            target: worker
        image: auction-worker:latest
        command: ["--task", "expire"]
        environment:
            NATS_ADDRESS: "nats:4222"
            REDIS_ADDRESS: "redis:6379"
        depends_on:
            nats:
                condition: service_healthy
            redis:
                condition: service_healthy
        networks:
            - isolated

    sell-worker:
        image: auction-worker:latest
        command: ["--task", "sell"]
        environment:
            NATS_ADDRESS: "nats:4222"
            REDIS_ADDRESS: "redis:6379"
        depends_on:
            nats:
                condition: service_healthy
            redis:
                condition: service_healthy
            expire-worker:
                condition: service_started
        networks:
            - isolated

    bid-worker:
        image: auction-worker:latest
        command: ["--task", "bid"]
        environment:
            NATS_ADDRESS: "nats:4222"
            REDIS_ADDRESS: "redis:6379"
        depends_on:
            nats:
                condition: service_healthy
            redis:
                condition: service_healthy
            expire-worker:
                condition: service_started
        networks:
            - isolated

    cancel-worker:
        image: auction-worker:latest
        command: ["--task", "cancel"]
        environment:
            NATS_ADDRESS: "nats:4222"
            REDIS_ADDRESS: "redis:6379"
        depends_on:
            nats:
                condition: service_healthy
            redis:
                condition: service_healthy
            expire-worker:
                condition: service_started
        networks:
            - isolated

    grpc-server:
        build:
            context: .
            target: server
        image: auction-server:latest
        environment:
            NATS_ADDRESS: "nats:4222"
            REDIS_ADDRESS: "redis:6379"
        depends_on:
            nats:
                condition: service_healthy
            redis:
                condition: service_healthy
            expire-worker:
                condition: service_started
            sell-worker:
                condition: service_started
        networks:
            - isolated
            - public
        ports:
            - 50051:50051

volumes:
    nats_jetstream:
    redis_data:

networks:
    isolated:
        internal: true
    public:
