services:
    nats:
        image: nats:latest
        command: ["--jetstream", "--store_dir", "/data", "--http_port", "8222"]
        networks:
            - isolated
        volumes:
            - nats_jetstream:/data

    redis:
        image: redis:8-alpine
        volumes:
            - redis_data:/data
        networks:
            - isolated
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 1m
            timeout: 3s
            retries: 5
            start_period: 5s

    expire-worker:
        build:
            context: .
            target: expire-worker
        image: auction-expire-worker:latest
        environment:
            NATS_ADDRESS: "nats:4222"
            REDIS_ADDRESS: "redis:6379"
        depends_on:
            nats:
                condition: service_started
            redis:
                condition: service_healthy
        networks:
            - isolated

    sell-worker:
        build:
            context: .
            target: sell-worker
        image: auction-sell-worker:latest
        environment:
            NATS_ADDRESS: "nats:4222"
            REDIS_ADDRESS: "redis:6379"
        depends_on:
            nats:
                condition: service_started
            redis:
                condition: service_healthy
            expire-worker:
                condition: service_started
        networks:
            - isolated

    grpc-server:
        build:
            context: .
            target: server
        image: auction-server:latest
        environment:
            NATS_ADDRESS: "nats:4222"
            REDIS_ADDRESS: "redis:6379"
        depends_on:
            nats:
                condition: service_started
            redis:
                condition: service_healthy
            expire-worker:
                condition: service_started
            sell-worker:
                condition: service_started
        networks:
            - isolated
            - public
        ports:
            - 50051:50051

volumes:
    nats_jetstream:
    redis_data:

networks:
    isolated:
        internal: true
    public:
