apiVersion: v1
kind: Service
metadata:
  name: {{ include "auction.fullname" . }}-grpc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "auction.fullname" . }}-grpc-server
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: grpc
