name: CI

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths-ignore:
            - ".gitignore"
            - "Dockerfile"
            - "compose.yaml"
            - "README.md"
            - "helm/**"
    pull_request:
        branches:
            - main
        paths-ignore:
            - ".gitignore"
            - "Dockerfile"
            - "compose.yaml"
            - "README.md"
            - "helm/**"

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        timeout-minutes: 2
        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-go@v7
              with:
                  go-version-file: go.mod
                  cache: true
                  cache-dependency-path: go.sum
            - run: go mod download
            - run: go test ./...
    gosec:
        name: Code Analysis
        runs-on: ubuntu-latest
        timeout-minutes: 2
        steps:
            - uses: actions/checkout@v7
            - uses: securego/gosec@v2.29.0
              with:
                  args: -exclude-generated ./...
